server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://grafana:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: status
            values: ["running"]
    relabel_configs:
      # Nom du container (sans le slash initial)
      - source_labels: [__meta_docker_container_name]
        regex: /(.*)
        target_label: container
      # Service docker-compose
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: service
      # stdout / stderr
      - source_labels: [__meta_docker_container_log_stream]
        target_label: stream
      # Image utilisée
      - source_labels: [__meta_docker_container_label_org_opencontainers_image_title]
        target_label: image
